### ISSUE TITLE
Feedback: General/Uncatgorized

### ISSUE THREAD

**Issue by nehamoopen** [UtrechtUniversity/workshop-introduction-to-R-and-data#32]
If you have any general feedback about the workshop that isn't specific to the Base R & `tidyverse` content, you can leave it here :)

**Comment by DorienHuijser** [comment]
Hello! I have not had time to go through the entire course (and I will not have time because of my holiday tomorrow), but I will paste what I had already written down, do with it what you want :)

- [ ] Can the URL to the materials be put in the repo description? Now I have to manually go to Deployments to find the correct link ;)
- [ ] README contains a LOT of links, what to start with? You have to download things but also see slides and videos. Can we make the order between all of the resources more clear?
- [ ] Make sure to remove the participants' names from the collaborative document after the workshop is finished. There are names in there now! > this is irrelevant if the workshop will move to offline
- [ ] README: the morning and afternoon session tables are structured differently. I think it would be better if they are structured the same, so html slides and a link to each question’s answer (e.g., https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/datascience_solutions.html#chapter-1-importing-data for chapter 1 etc.)

**Comment by DorienHuijser** [comment]
Suggestion from a workshop participant: create a really basic cheatsheet about what has been discussed in the workshop (with basic words like what is a vector, dataframe, etc. and some basic tidyverse functions etc.)

**Comment by DorienHuijser** [comment]
Make sure the slides are rendered to pdf and downloadable that way
